<?php

namespace AppBundle\Repository;

/**
 * ShopMasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopMasterRepository extends \Doctrine\ORM\EntityRepository
{
}
