shop_master_index:
    path:     /index
    defaults: { _controller: AppBundle:ShopMaster:index }
   
shop_master_save:
    path:     /save
    defaults: { _controller: AppBundle:ShopMaster:save }
    